trigger:
- master


# Build Stage
stages:
- stage: 'QA'
  displayName: "Build and Push"
  jobs:
  - job: Build
    displayName: Build & Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

      - checkout: self

      - template: DockerBuild.yml
        parameters:
          ProjectName: 'angular-app'
          ConnectionTypeName: 'foodalert-prakash'
          RegistryServiceConnection: 'Acr-connection'
          WebAppName: 'appservicefoodalerttest0000'
          repository: 'udayangular'
          containerRegistry: udaycontainer.azurecr.io
          tag: 'Build-$(Build.BuildNumber)'
          token: 'false'
