trigger:
- master


# Build Stage
stages:
- stage: 'QA'
  displayName: "Build and Push"
  jobs:
  - job: Build
    displayName: Build & Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

      - checkout: self

      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '6.x'
      - script: |
          npm install -g @angular/cli@^9
          npm install
          ng build --prod